version: '3'

services:
  app:
    build:
      context: .
    environment:
      RAILS_ENV: development
      RAILS_LOG_TO_STDOUT: 1
    volumes:
      - ./docker/database.yml:/app/config/database.yml
      - ./docker/unicorn.rb:/app/config/unicorn.rb
      - unicorn:/unicorn
      - assets:/assets
    depends_on:
      - db

  nginx:
    image: nginx
    depends_on: [app]
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./public:/public:ro
      - unicorn:/unicorn
      - assets:/public
    labels:
      - traefik.frontend.rule=Host:localhost

  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql-converter-maz/data

volumes:
  db:
  unicorn:
  assets:
