version: '3'

services:
  app:
    build:
      context: .

  nginx:
    labels:
      - traefik.frontend.rule=Host:localhost

  reverse-proxy:
    image: traefik
    command: --api --docker
    ports:
      - 7000:80
      - 8084:8080

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # - ./config/traefik.toml:/traefik.toml

  db:
    volumes:
      - ./init:/docker-entrypoint-initdb.d:ro
